### ISSUE TITLE
http://127.0.0.1:5500/3d-obj-loader/assets/scene.gltf not found 

### ISSUE THREAD

**Issue by impsdc** [SekeNikola/ThreeJS-GLTF-loader#1]
I just clone the project and run it with live server and get 404 on the scene.gltf file.

**Comment by SekeNikola** [comment]
Added to readme file.

**Comment by impsdc** [comment]
@SekeNikola there is a misunderstanding i get an error for the importation of the scene.gltf file. To reproduce my issue just clone the repo and run it with live server.

**Comment by impsdc** [comment]
Ok the import of scene.gltf is not working on localhost, cause of file import security. So you need to put the project in a virtual host

**Comment by SekeNikola** [comment]
> Ok the import of scene.gltf is not working on localhost, cause of file import security. So you need to put the project in a virtual host

Sorry didn't understand a question the first time.  As I wrote in readme file files has to be run in Live Server or Virtual Server.

**Comment by impsdc** [comment]
Live Server does not seem to work ... I think Virtual Server is the only solution

**Comment by SekeNikola** [comment]
> Live Server does not seem to work ... I think Virtual Server is the only solution

When I say Liver Server am referencing to Live server on Visual Studio Code or on Virtual server as you mention

**Comment by impsdc** [comment]
Yeah i know but launching the projet with the extension Live Server on VScode does not work with me. I got the 404 not found of the scene.gltf file.

**Comment by SekeNikola** [comment]
> Yeah i know but launching the projet with the extension Live Server on VScode does not work with me. I got the 404 not found of the scene.gltf file.

I just opened in VS Live server and its working fine??? Hmmmm interesting 
![image](https://user-images.githubusercontent.com/32386925/95877777-c193fa00-0d74-11eb-9047-a43cacac3c85.png)
